----------------------------------------------------------------------
-- 04_create_semantic_view.sql
-- Cortex Analyst Semantic View
----------------------------------------------------------------------
-- Open the Cortex Code panel and try the prompt from the README:
--
-- PROMPT — Create semantic view:
--   "Create a Cortex Analyst semantic view called
--    QUICKSTART_DB.ANALYTICS.CUSTOMER_ANALYTICS_SV over the
--    QUICKSTART_DB.ANALYTICS.CUSTOMER_SUMMARY table. Include
--    meaningful descriptions for all columns and define common
--    metrics like total_revenue and avg_order_value."
--
-- PROMPT — Test the semantic view:
--   "Use the QUICKSTART_DB.ANALYTICS.CUSTOMER_ANALYTICS_SV semantic
--    view to answer: 'Which region has the highest average order
--    value?'"
--
-- After each prompt, review the diff, apply, and run the SQL.
-- Then commit and push from the Changes tab.
----------------------------------------------------------------------
